### ISSUE TITLE
Urm, not too sure about what is happening

### ISSUE THREAD

**Issue by LinuxGamer** [ChrisTitusTech/Fedora-Titus#2]
![image](https://user-images.githubusercontent.com/83363242/165168521-a45eff6c-5fa8-475c-8176-fbf1e9d5ec15.png)

I have added the .xresources and .xnord to my /.config folder - if you can think of anything that i'm doing wrong, please let me know - cheers

**Comment by arDrag0n** [comment]
copy the xresources and xnord to the home folder and dotconfig folder files to ~/.config and the run the script from ~/.config/polybar
