### ISSUE TITLE
What Fadora ISO are you using? 

### ISSUE THREAD

**Issue by eXsoR65** [ChrisTitusTech/Fedora-Titus#7]
I tried to follow your video on installing fedora on a old laptop but wanted to customize it. I downloaded the Fedora Standard Server 36 image and for packages it didn't have window manager to anything else you selected. 

Did you maybe use the netiso?

**Comment by rafay99-epic** [comment]
## Solution;
Yeah Bro, That will not work... There are two version of ISO, One with everything is installed, internet is not required and second  where you will choose and download everypackages while installing but an internet connection is required, you might be using the first ISO. so use the second ISO.
## Download Link
Link: https://getfedora.org/en/server/download/
## Picture:
![Screenshot (3)](https://user-images.githubusercontent.com/82662797/178934395-7086a9a2-e092-4745-94b3-49eb923cf5d0.png)

**Comment by eXsoR65** [comment]
> ## Solution;
> 
> Yeah Bro, That will not work... There are two version of ISO, One with everything is installed, internet is not required and second  where you will choose and download everypackages while installing but an internet connection is required, you might be using the first ISO. so use the second ISO.
> 
> ## Download Link
> 
> Link: https://getfedora.org/en/server/download/
> 
> ## Picture:
> 
> ![Screenshot (3)](https://user-images.githubusercontent.com/82662797/178934395-7086a9a2-e092-4745-94b3-49eb923cf5d0.png)
> 
> 
> 
> 

Fair enough! Should have tried it before asking 😅 but thank you for your help.

**Comment by rafay99-epic** [comment]
Always here to help...
